package com.edusphere.ai.enums;

public enum AiIntent {
    ACADEMIC_OVERVIEW,
    INTERNAL_MARKS,
    SEMESTER_MARKS,
    GPA,
    CGPA,
    ACADEMIC_HISTORY,
    PERFORMANCE_COMPARISON,
    PERFORMANCE_TREND,
    SUBJECT_PERFORMANCE,
    STRENGTH_ANALYSIS,
    WEAKNESS_ANALYSIS,
    ACADEMIC_RECOMMENDATION,
    CERTIFICATE_STATUS,
    CERTIFICATE_LIST,
    CODING_PROFILE,
    GITHUB_ANALYSIS,
    LEETCODE_ANALYSIS,
    COMBINED_ACADEMIC_CODING_ANALYSIS,
    ACADEMIC_REPORT,
    GENERAL_ACADEMIC,
    GENERAL_CHAT
}
